name: swift project

on:
 push:
  branches:
   - main
   - master

env:
  XCODE_VERSION: '16.1'
  PROJECT_NAME: 'build-test-ios'
  SCHEME_NAME: 'build-test-ios'   

jobs:
 build:
  runs-on: macos-latest

  steps:
   - name: checkout the code
     uses: actions/checkout@v4

   - name: Setup Xcode
     uses: maxim-lobanov/setup-xcode@v1
     with:
         xcode-version: ${{ env.XCODE_VERSION }}
          
   - name: Cache derived data
     uses: actions/cache@v4
     with:
       path: ~/Library/Developer/Xcode/DerivedData
       key: ${{ runner.os }}-derived-data-${{ matrix.configuration }}-${{ hashFiles('**/*.xcodeproj') }}
       restore-keys: |
          ${{ runner.os }}-derived-data-${{ matrix.configuration }}-
          ${{ runner.os }}-derived-data-
            
   - name: Build for iOS Simulator
     run: |
          set -o pipefail
          xcodebuild clean build \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -configuration ${{ matrix.configuration }} \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.1" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            | xcpretty
