name: ci workflow

on:
 push:
  branches:
   - main

jobs:
  lint:
   runs-on: macos-latest

   steps:
    - name: checkout the code 
      uses: actions/checkout@v4

    - name: install swiftlint
      run: brew install swiftlint

    - name: Run swiftlint
      run: swiftlint

  test:
   needs: [lint]
   runs-on: macos-latest
   strategy:
     matrix:
      destination: 
        - destination "platform=visionOS Simulator,id=6B240C3E-0355-4A8E-8FD7-4F2B48B7F341,OS=2.2"
        
   steps:
    - name: checkout the code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.app

    - name: Upload xcresult bundle
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: TestResult${{ strategy.job-index }}.xcresult

    - name: Build and Test
      run: |
        set -o pipefail
        xcodebuild \
        -project lint-test-ios/lint-test-ios.xcodeproj \
        -scheme lint-test-ios \
        -destination "${{ matrix.destination }}" \
        -resultBundlePath Testresults-${{ strategy.job-index }} \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGN_IDENTITY="" \
        PROVISIONING_PROFILE_SPECIFIER="" \
        ONLY_ACTIVE_ARCH=YES \
        | xcpretty --report junit --output test-result.xml

        
