name: swift ci workflow

on:
 push:
  branches:
   - main
   - master

jobs:
 build:
  runs-on: macos-latest

  steps:
   - name: checkout the code
     uses: actions/checkout@v4

   - name: set up swift
     run: swift --version

   - name: compile with swiftc
     run: swiftc main.swift o- output

   - name: run the compiled program
     run: ./output

    
   
