name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
        
      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
        continue-on-error: true  # Set to false if you want to fail on lint warnings/errors

     # - name: List directory contents
       # run: |
       #    pwd
        #   ls -la
         #  find . -name "*.xcodeproj" -o -name "*.xcworkspace" -o -name "Package.swift"

  unit-test:
    needs: lint
    runs-on: macos-latest

    steps:
     - name: check out the code
       uses: actions/checkout@v4

     - name: Setup Xcode
       uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: '15.0.1' 

     - name: Run Unit Tests
       run: swift test
                  
  build:
     needs: [lint, unit-test]
     runs-on: macos-latest

     steps:
     - name: checkout the code
       uses: actions/checkout@v4
  
     - name: Build Project
       run: |
          xcodebuild clean build \
           -project lint-test-ios/lint-test-ios.xcodeproj \
           -scheme lint-test-ios \
           -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
