name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app  # Adjust based on available versions

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
        continue-on-error: true  # Set to false if you want to fail on lint warnings/errors

      - name: Install Dependencies (if using SwiftPM)
        run: swift package resolve

      - name: Build Project
        run: |
          xcodebuild clean build \
            -scheme lint-test-ios \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -scheme lint-test-ios \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'

