name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: install swiftlint
      run: brew install swiftlint

    - name: run swiftlint
      run: swiftlint

  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show project directory (debug)
        run: ls -R

      - name: Run unit tests
        run: |
          xcodebuild clean build test \ || echo "something"
            -project lint-test-ios.xcodeproj \ || echo "there is a some issue in xcode"
            -scheme lint-test-ios \ || echo " there is a some issue in scheme"
            -sdk iphonesimulator \ || echo " there is a some issue in sdk"
            -destination "platform=iOS Simulator,name=iPhone 14" || echo"there is a some issue in destination"
   
 # build:
  #  needs: [lint]
   # runs-on: macos-latest

    #steps:
     #- name: checkout the code
      # uses: actions/checkout@v4

       
     #- name: Set up Ruby for CocoaPods
      # uses: ruby/setup-ruby@v1
       #with:
        #ruby-version: '3.1'

     #- name: Install CocoaPods
      # run: pod install

     #- name: debug
      # run: |
       # echo "Current directory: $(pwd)"
        #ls -R

     #- name: Build and test
      # run: |
       #  cd lint-test-ios
        # xcodebuild clean build test \
         #-project lint-test-ios.xcodeproj \
         #-scheme lint-test-ios \
         #-sdk iphonesimulator \
         #-destination 'platform=iOS Simulator,name=iPhone 14'
 
