name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app  # Adjust based on available versions

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
        continue-on-error: true  # Set to false if you want to fail on lint warnings/errors

      - name: List directory contents
        run: |
           pwd
           ls -la
           find . -name "*.xcodeproj" -o -name "*.xcworkspace" -o -name "Package.swift"
